title: Homebrew Catalog Frontend by fierymewtwo
description: A homebrew catalog built entirely on GitHub Pages
social_link: instagram
social_username: mochathebeardie
github_repo: hbpackages-fileserver
github_username: FieryMewtwo
theme_color: black
remote_theme: internet-de-france/swiss
baseurl: /hbcatalog
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
